import { Schema, model } from "mongoose";

// ---------------- Notification ----------------
const notificationSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    body: {
      type: String,
      required: true,
      trim: true,
    },
    type: {
      type: String,
      enum: [
        "assistant_assigned",
        "application_progress",
        "new_message",
        "billing_update",
        "account_alert",
      ],
      default: "account_alert",
    },
    read: {
      type: Boolean,
      default: false,
      index: true,
    },
  },
  { timestamps: true },
);
export const Notification = model("Notification", notificationSchema);

// ---------------- Preferences ----------------
const preferenceSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      unique: true,
      index: true,
      required: true,
    },
    emailUpdates: { type: Boolean, default: true },
    whatsappUpdates: { type: Boolean, default: false },
    dailyProgressReport: { type: Boolean, default: true },
    escalationAlerts: { type: Boolean, default: true },
    autoGenerateDocuments: { type: Boolean, default: true },
    assistantUpdates: { type: Boolean, default: true },
  },
  { timestamps: true },
);

export const Preference = model("Preference", preferenceSchema);

// ---------------- Application Answers ----------------
const applicationAnswerSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      unique: true,
      index: true,
      required: true,
    },
    answers: {
      workAuthorization: String,
      sponsorshipNeeded: Boolean,
      locations: [String],
      relocation: Boolean,
      workType: String,
      salaryRange: String,
      jobTitles: [String],
      seniorityLevel: String,
      industries: [String],
      startDate: String,
      contractOpen: Boolean,
      travelOpen: Boolean,
      veteranStatus: Boolean,
      visaSupport: Boolean,
    },
  },
  { timestamps: true },
);

export const ApplicationAnswer = model(
  "ApplicationAnswer",
  applicationAnswerSchema,
);

// ---------------- Audit Log ----------------
const auditLogSchema = new Schema(
  {
    actorId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      index: true,
    },
    action: {
      type: String,
      required: true,
    },
    targetType: String,
    targetId: String,
    metadata: Object,
  },
  { timestamps: true },
);

export const AuditLog = model("AuditLog", auditLogSchema);

// ---------------- Activity Log ----------------
const activityLogSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      index: true,
    },
    event: {
      type: String,
      required: true,
    },
    metadata: Object,
  },
  { timestamps: true },
);

export const ActivityLog = model("ActivityLog", activityLogSchema);
