import { Router, Request, Response, NextFunction } from "express";
import { z } from "zod";
import { requireAuth, requireRole } from "../middleware/authMiddleware";
import { Job } from "../models/Job";
import { SavedJob } from "../models/SavedJob";
import { DelegatedJob } from "../models/DelegatedJob";
import {
  ApplicationAnswer,
  Notification,
  Preference,
} from "../models/AppMetaModels";
import { EmailMessage, EmailThread } from "../models/InboxModels";
import { Task } from "../models/Task";
import { Subscription } from "../models/BillingModels";
import { SubscriptionPlan } from "../models/SubscriptionPlan";
import { ChatThread } from "../models/ChatThread";
import { ChatMessage } from "../models/ChatMessage";
import { User } from "../models/User";

const router = Router();

const asyncHandler =
  (fn: (req: Request, res: Response, next: NextFunction) => Promise<void>) =>
  (req: Request, res: Response, next: NextFunction) => {
    Promise.resolve(fn(req, res, next)).catch(next);
  };

const objectIdParamSchema = z.object({
  id: z.string().min(1, "Missing id param"),
});

const saveJobSchema = z.object({
  status: z.enum(["saved", "archived"]).optional().default("saved"),
});

const delegateJobSchema = z.object({
  assistantId: z.string().min(1, "assistantId is required"),
  notes: z.string().max(2000).optional().default(""),
});

const chatMessageSchema = z.object({
  body: z.string().trim().min(1, "Message body is required").max(5000),
  attachments: z.array(z.any()).optional().default([]),
});

const subscribeSchema = z.object({
  planId: z.string().min(1, "planId is required"),
});

const applicationAnswersSchema = z.object({
  answers: z.record(z.any()),
});

const preferencesSchema = z.object({
  emailUpdates: z.boolean().optional(),
  whatsappUpdates: z.boolean().optional(),
  dailyProgressReport: z.boolean().optional(),
  escalationAlerts: z.boolean().optional(),
  autoGenerateDocuments: z.boolean().optional(),
  assistantNotifications: z.boolean().optional(),
  preferredLocations: z.array(z.string()).optional(),
  remotePreference: z.enum(["remote", "hybrid", "onsite", "any"]).optional(),
  salaryMin: z.number().optional(),
  salaryMax: z.number().optional(),
  targetTitles: z.array(z.string()).optional(),
});

function getPagination(req: Request) {
  const page = Math.max(Number(req.query.page) || 1, 1);
  const limit = Math.min(Math.max(Number(req.query.limit) || 20, 1), 100);
  const skip = (page - 1) * limit;
  return { page, limit, skip };
}

function ok(res: Response, data: unknown, meta?: Record<string, unknown>) {
  return res.json({
    success: true,
    data,
    ...(meta ? { meta } : {}),
  });
}

function created(res: Response, data: unknown) {
  return res.status(201).json({
    success: true,
    data,
  });
}

function ensureUser(req: Request) {
  if (!req.user) {
    const err = new Error("Unauthorized");
    (err as any).statusCode = 401;
    throw err;
  }
  return req.user;
}

function badRequest(message: string) {
  const err = new Error(message);
  (err as any).statusCode = 400;
  return err;
}

function forbidden(message = "Forbidden") {
  const err = new Error(message);
  (err as any).statusCode = 403;
  return err;
}

function notFound(message = "Resource not found") {
  const err = new Error(message);
  (err as any).statusCode = 404;
  return err;
}

/**
 * GET /jobs
 * Public to authenticated users
 * Supports search + filters + pagination
 */
router.get(
  "/jobs",
  requireAuth,
  asyncHandler(async (req, res) => {
    const { page, limit, skip } = getPagination(req);
    const search = String(req.query.search || "").trim();
    const location = String(req.query.location || "").trim();
    const remoteType = String(req.query.remoteType || "").trim();

    const query: Record<string, any> = {};

    if (search) {
      query.$or = [
        { title: { $regex: search, $options: "i" } },
        { company: { $regex: search, $options: "i" } },
        { skills: { $elemMatch: { $regex: search, $options: "i" } } },
      ];
    }

    if (location) {
      query.location = { $regex: location, $options: "i" };
    }

    if (remoteType) {
      query.remoteType = remoteType;
    }

    const [items, total] = await Promise.all([
      Job.find(query)
        .sort({ postedAt: -1, createdAt: -1 })
        .skip(skip)
        .limit(limit),
      Job.countDocuments(query),
    ]);

    ok(res, items, {
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    });
  }),
);

/**
 * POST /jobs/:id/save
 */
router.post(
  "/jobs/:id/save",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const { id } = objectIdParamSchema.parse(req.params);
    const body = saveJobSchema.parse(req.body || {});

    const job = await Job.findById(id);
    if (!job) throw notFound("Job not found");

    const saved = await SavedJob.findOneAndUpdate(
      { clientId: user.id, jobId: id },
      {
        $set: {
          clientId: user.id,
          jobId: id,
          status: body.status,
        },
      },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );

    ok(res, saved);
  }),
);

/**
 * POST /jobs/:id/delegate
 */
router.post(
  "/jobs/:id/delegate",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const { id } = objectIdParamSchema.parse(req.params);
    const body = delegateJobSchema.parse(req.body);

    const [job, assistant] = await Promise.all([
      Job.findById(id),
      User.findById(body.assistantId),
    ]);

    if (!job) throw notFound("Job not found");
    if (!assistant) throw notFound("Assistant not found");

    if (assistant.role !== "assistant" && assistant.role !== "admin") {
      throw badRequest("Selected user is not an assistant");
    }

    const delegated = await DelegatedJob.create({
      clientId: user.id,
      assistantId: body.assistantId,
      jobId: id,
      status: "new",
      notes: body.notes,
    });

    created(res, delegated);
  }),
);

/**
 * GET /inbox
 * Only fetch this user's threads + messages
 */
router.get(
  "/inbox",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);

    const threads = await EmailThread.find({ userId: user.id }).sort({
      updatedAt: -1,
    });

    const threadIds = threads.map((thread: any) => thread._id);

    const messages = await EmailMessage.find({
      threadId: { $in: threadIds },
    })
      .sort({ createdAt: -1 })
      .limit(50);

    ok(res, {
      threads,
      messages,
    });
  }),
);

/**
 * GET /chat/threads
 */
router.get(
  "/chat/threads",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);

    const threads = await ChatThread.find({
      participantIds: user.id,
    }).sort({ updatedAt: -1 });

    ok(res, threads);
  }),
);

/**
 * GET /chat/threads/:id/messages
 */
router.get(
  "/chat/threads/:id/messages",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const { id } = objectIdParamSchema.parse(req.params);

    const thread = await ChatThread.findById(id);
    if (!thread) throw notFound("Chat thread not found");

    const isParticipant =
      Array.isArray((thread as any).participantIds) &&
      (thread as any).participantIds.some(
        (participantId: any) => String(participantId) === String(user.id),
      );

    if (!isParticipant && user.role !== "admin") {
      throw forbidden("You do not have access to this thread");
    }

    const messages = await ChatMessage.find({ threadId: id }).sort({
      createdAt: 1,
    });

    ok(res, messages);
  }),
);

/**
 * POST /chat/threads/:id/messages
 */
router.post(
  "/chat/threads/:id/messages",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const { id } = objectIdParamSchema.parse(req.params);
    const body = chatMessageSchema.parse(req.body);

    const thread = await ChatThread.findById(id);
    if (!thread) throw notFound("Chat thread not found");

    const isParticipant =
      Array.isArray((thread as any).participantIds) &&
      (thread as any).participantIds.some(
        (participantId: any) => String(participantId) === String(user.id),
      );

    if (!isParticipant && user.role !== "admin") {
      throw forbidden("You do not have access to send messages in this thread");
    }

    const message = await ChatMessage.create({
      threadId: id,
      senderId: user.id,
      body: body.body,
      attachments: body.attachments,
    });

    await ChatThread.findByIdAndUpdate(id, {
      $set: { updatedAt: new Date() },
    });

    created(res, message);
  }),
);

/**
 * GET /plans
 * Public within app
 */
router.get(
  "/plans",
  asyncHandler(async (_req, res) => {
    const plans = await SubscriptionPlan.find({ active: true }).sort({
      priceMonthly: 1,
    });
    ok(res, plans);
  }),
);

/**
 * POST /billing/subscribe
 */
router.post(
  "/billing/subscribe",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const body = subscribeSchema.parse(req.body);

    const plan = await SubscriptionPlan.findById(body.planId);
    if (!plan) throw notFound("Plan not found");

    const sub = await Subscription.create({
      userId: user.id,
      planId: body.planId,
      status: "active",
      provider: process.env.STRIPE_SECRET_KEY ? "stripe" : "mock",
      currentPeriodStart: new Date(),
      currentPeriodEnd: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    });

    ok(res, sub);
  }),
);

/**
 * GET /application-answers
 */
router.get(
  "/application-answers",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const answers = await ApplicationAnswer.findOne({ userId: user.id });
    ok(res, answers ?? { userId: user.id, answers: {} });
  }),
);

/**
 * PUT /application-answers
 */
router.put(
  "/application-answers",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const body = applicationAnswersSchema.parse(req.body);

    const answers = await ApplicationAnswer.findOneAndUpdate(
      { userId: user.id },
      {
        $set: {
          userId: user.id,
          answers: body.answers,
        },
      },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );

    ok(res, answers);
  }),
);

/**
 * GET /notifications
 */
router.get(
  "/notifications",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const items = await Notification.find({ userId: user.id })
      .sort({ createdAt: -1 })
      .limit(50);

    ok(res, items);
  }),
);

/**
 * GET /account/preferences
 */
router.get(
  "/account/preferences",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const prefs = await Preference.findOne({ userId: user.id });

    ok(
      res,
      prefs ?? {
        userId: user.id,
        emailUpdates: true,
        whatsappUpdates: false,
        dailyProgressReport: true,
        escalationAlerts: true,
        autoGenerateDocuments: false,
        assistantNotifications: true,
      },
    );
  }),
);

/**
 * PUT /account/preferences
 */
router.put(
  "/account/preferences",
  requireAuth,
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);
    const body = preferencesSchema.parse(req.body);

    const prefs = await Preference.findOneAndUpdate(
      { userId: user.id },
      { $set: { ...body, userId: user.id } },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );

    ok(res, prefs);
  }),
);

/**
 * GET /assistant/dashboard
 */
router.get(
  "/assistant/dashboard",
  requireAuth,
  requireRole("assistant", "admin"),
  asyncHandler(async (req, res) => {
    const user = ensureUser(req);

    const [delegatedCount, dueToday, blockedCount, recentDelegated] =
      await Promise.all([
        DelegatedJob.countDocuments({
          assistantId: user.id,
          status: { $in: ["new", "in_progress", "needs_client_input"] },
        }),
        Task.countDocuments({
          assistantId: user.id,
          dueAt: { $lte: new Date() },
          status: { $ne: "done" },
        }),
        DelegatedJob.countDocuments({
          assistantId: user.id,
          status: "blocked",
        }),
        DelegatedJob.find({ assistantId: user.id })
          .sort({ updatedAt: -1 })
          .limit(5)
          .populate("jobId")
          .populate("clientId", "fullName email"),
      ]);

    ok(res, {
      delegatedCount,
      dueToday,
      blockedCount,
      recentDelegated,
    });
  }),
);

/**
 * GET /admin/overview
 */
router.get(
  "/admin/overview",
  requireAuth,
  requireRole("admin"),
  asyncHandler(async (_req, res) => {
    const [users, jobs, delegated, chats, activeSubscriptions] =
      await Promise.all([
        User.countDocuments(),
        Job.countDocuments(),
        DelegatedJob.countDocuments(),
        ChatThread.countDocuments(),
        Subscription.countDocuments({ status: "active" }),
      ]);

    ok(res, {
      users,
      jobs,
      delegated,
      chats,
      activeSubscriptions,
    });
  }),
);

export default router;
